### ISSUE TITLE
How to parse goejson  with this binding

### ISSUE THREAD

**Issue by ghost** [MangelMaxime/Fable.Geojson#2]
I do not know why I can only "parse" raw string to entire geojson module like this: 

`Decode.Auto.fromString<Geojson>`

Then I can access features with dynamic operator.
Of course I would like to have everything strongly typed but  whenether I try to use Point ofr GeometryCollection with my own Properties object I'm getting message to pass proper Decoder first:

`Decode.Auto.fromString<GeometryCollection, NameProperties> raw`

Is there some limitation or I'm using the binding wrongly?

PS: Is this binding going to be included in Thoth anytime? Or it is not so prevalent to be in common realm

**Comment by MangelMaxime** [comment]
Hello, the error message should indeed ask you to pass the extra decoder. 

This will not be included to `Thoth.Json` by default, because this would increase the bundle size for all the application even if they don't use the type.

If you are working with `Auto coders`, you should probably create helpers which provide all the extra coders you use in your application.

**Comment by MangelMaxime** [comment]
Someone bumped into this issue again on Gitter.

Here is an example of how the code could looks like: https://gist.github.com/MangelMaxime/23fa8091574be9346b852d9027fbb76a

In theory, it's possible to register the decoder using extra module in order to have access to them from Decode.Auto

I am closing this issue because there is not much we can do from this repo about it.
